#runtime: python
#env: flex
#entrypoint: gunicorn -b :$PORT main:app

#runtime_config:
#  python_version: 3

runtime: python37
entrypoint: gunicorn -b 0.0.0.0:8080 demo:server

#handlers:
#  - url: /.*
#    script: demo.app